C = gcc
CXX = clang++
SOURCE_C = program.c
#OBJECTS_C = program.o
SOURCE_CXX = program.cpp
TARGET = program
LDFLAGS_COMMON = -std=c++2a

# all:
# 	$(C) -c $(SOURCE_C)     											
# 	$(CXX) $(SOURCE_CXX) $(OBJECTS_C) $(LDFLAGS_COMMON) -o $(TARGET) 	

# clean:
# 	rm -rf *.o $(TARGET)

all:
	$(CXX) $(SOURCE_CXX) $(LDFLAGS_COMMON) -o $(TARGET)

