C = gcc
CXX = clang++
SOURCE_C = helloworld.c
#OBJECTS_C = helloworld.o
SOURCE_CXX = helloworld.cpp
TARGET = helloworld
LDFLAGS_COMMON = -std=c++2a

# all:
# 	$(C) -c $(SOURCE_C)     											
# 	$(CXX) $(SOURCE_CXX) $(OBJECTS_C) $(LDFLAGS_COMMON) -o $(TARGET) 	

# clean:
# 	rm -rf *.o $(TARGET)

all:
	$(CXX) $(SOURCE_CXX) $(LDFLAGS_COMMON) -o $(TARGET)

